- name: Install Python build dependencies
  apt:
    name:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - git
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
    update_cache: true

- name: Install pyenv
  shell: curl https://pyenv.run | bash

- name: Add pyenv to PATH in .bashrc
  shell: |
      echo 'export PATH="/root/.pyenv/bin:$PATH"' >> /root/.bashrc
      echo 'eval "$(pyenv init --path)"' >> /root/.bashrc
      echo 'eval "$(pyenv init -)"' >> /root/.bashrc
  args:
    executable: /bin/bash

- name: Apply the changes to the current session
  shell: . /root/.bashrc
  args:
    executable: /bin/bash

- name: Create a directory named python3.7
  file:
    path: /root/python3.7
    state: directory
    mode: '0644'

- name: Create a directory named python3.12
  file:
    path: /root/python3.12
    state: directory
    mode: '0644'

- name: Install python3.7
  shell: |
    /root/.pyenv/bin/pyenv install 3.7.4
  args:
    executable: /bin/bash

- name: Install python3.12
  shell: |
    /root/.pyenv/bin/pyenv install 3.12.4
  args:
    executable: /bin/bash

- name: Set local Python version to 3.7.0 in /root/python3.7
  shell: /root/.pyenv/bin/pyenv local 3.7.4
  args:
    chdir: /root/python3.7
    executable: /bin/bash

- name: Set local Python version to 3.12 in /root/python3.12
  shell: /root/.pyenv/bin/pyenv local 3.12.4
  args:
    chdir: /root/python3.12
    executable: /bin/bash
